// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMi87VSk8CyjRZxw9jimpCuQdKzcTnz10',
    appId: '1:130165126836:web:4e9a4b8d163fac520e89e1',
    messagingSenderId: '130165126836',
    projectId: 'hurst-d954d',
    authDomain: 'hurst-d954d.firebaseapp.com',
    storageBucket: 'hurst-d954d.appspot.com',
    measurementId: 'G-DB2JZQX24D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3cHX2QjGzKu-5UjJxPW0DxoMw0s0q0lM',
    appId: '1:130165126836:android:f23735e4a63760ca0e89e1',
    messagingSenderId: '130165126836',
    projectId: 'hurst-d954d',
    storageBucket: 'hurst-d954d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8g_RiJyGNqrmkDPhIBvO6XAocnHxxcY',
    appId: '1:130165126836:ios:e14e233eb55d993a0e89e1',
    messagingSenderId: '130165126836',
    projectId: 'hurst-d954d',
    storageBucket: 'hurst-d954d.appspot.com',
    iosClientId: '130165126836-hkpperip3i3jespns002to5a2d471bb8.apps.googleusercontent.com',
    iosBundleId: 'br.com.hurst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS8g_RiJyGNqrmkDPhIBvO6XAocnHxxcY',
    appId: '1:130165126836:ios:257fa70b397a1a180e89e1',
    messagingSenderId: '130165126836',
    projectId: 'hurst-d954d',
    storageBucket: 'hurst-d954d.appspot.com',
    iosClientId: '130165126836-7seshm29ik7e5jreaf141qa65e4rbnji.apps.googleusercontent.com',
    iosBundleId: 'br.com.hurst.RunnerTests',
  );
}
